services:
  web:
    image: nginx
    ports:
      - "80"
    networks:
      - app-network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - app-network
    volumes:
        - db-data:/var/lib/mysql
  admin:
      image: phpmyadmin/phpmyadmin
      environment:
          PMA_HOST: db
      ports:
          - "8081:80"
      networks:
          - app-network
networks:
  app-network:
volumes:
  db-data: